{
  "uid" : "8904cc2d1ed62861",
  "name" : "An uncaught error was detected outside of a test",
  "fullName" : "An uncaught error was detected outside of a test",
  "historyId" : "c59643030e1e776644fd5d1d6aa79cfc",
  "time" : {
    "start" : 1662777892030,
    "stop" : 1662777892166,
    "duration" : 136
  },
  "status" : "failed",
  "statusMessage" : "The following error originated from your test code, not from Cypress.\n\n  > Expected to find a global registry (this usually means you are trying to define steps or hooks in support/e2e.js, which is not supported) (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
  "statusTrace" : "Error: The following error originated from your test code, not from Cypress.\n\n  > Expected to find a global registry (this usually means you are trying to define steps or hooks in support/e2e.js, which is not supported) (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at fail (http://localhost:41299/__cypress/tests?p=cypress/e2e/cucumber/examples/steps.cy.js:17:11)\n    at assert (http://localhost:41299/__cypress/tests?p=cypress/e2e/cucumber/examples/steps.cy.js:24:5)\n    at assertAndReturn (http://localhost:41299/__cypress/tests?p=cypress/e2e/cucumber/examples/steps.cy.js:28:5)\n    at getRegistry (http://localhost:41299/__cypress/tests?p=cypress/e2e/cucumber/examples/steps.cy.js:544:45)\n    at defineStep (http://localhost:41299/__cypress/tests?p=cypress/e2e/cucumber/examples/steps.cy.js:320:32)\n    at eval (http://localhost:41299/__cypress/tests?p=cypress/e2e/cucumber/examples/steps.cy.js:11725:79)\n    at eval (http://localhost:41299/__cypress/tests?p=cypress/e2e/cucumber/examples/steps.cy.js:11764:3)\n    at eval (http://localhost:41299/__cypress/tests?p=cypress/e2e/cucumber/examples/steps.cy.js:11766:12)\n    at eval (<anonymous>)",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "The following error originated from your test code, not from Cypress.\n\n  > Expected to find a global registry (this usually means you are trying to define steps or hooks in support/e2e.js, which is not supported) (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
    "statusTrace" : "Error: The following error originated from your test code, not from Cypress.\n\n  > Expected to find a global registry (this usually means you are trying to define steps or hooks in support/e2e.js, which is not supported) (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at fail (http://localhost:41299/__cypress/tests?p=cypress/e2e/cucumber/examples/steps.cy.js:17:11)\n    at assert (http://localhost:41299/__cypress/tests?p=cypress/e2e/cucumber/examples/steps.cy.js:24:5)\n    at assertAndReturn (http://localhost:41299/__cypress/tests?p=cypress/e2e/cucumber/examples/steps.cy.js:28:5)\n    at getRegistry (http://localhost:41299/__cypress/tests?p=cypress/e2e/cucumber/examples/steps.cy.js:544:45)\n    at defineStep (http://localhost:41299/__cypress/tests?p=cypress/e2e/cucumber/examples/steps.cy.js:320:32)\n    at eval (http://localhost:41299/__cypress/tests?p=cypress/e2e/cucumber/examples/steps.cy.js:11725:79)\n    at eval (http://localhost:41299/__cypress/tests?p=cypress/e2e/cucumber/examples/steps.cy.js:11764:3)\n    at eval (http://localhost:41299/__cypress/tests?p=cypress/e2e/cucumber/examples/steps.cy.js:11766:12)\n    at eval (<anonymous>)",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "d10cbdab21a56576",
      "name" : "cypress/e2e/cucumber/examples/steps.cy.js:2022-09-10T02:44:52.060Z",
      "source" : "d10cbdab21a56576.png",
      "type" : "image/png",
      "size" : 26604
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 4,
        "broken" : 0,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 4
      },
      "items" : [ {
        "uid" : "625406222a6bf85d",
        "status" : "failed",
        "statusDetails" : "The following error originated from your test code, not from Cypress.\n\n  > Expected to find a global registry (this usually means you are trying to define steps or hooks in support/e2e.js, which is not supported) (this might be a bug, please report at https://github.com/badeball/cypress-cucumber-preprocessor)\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
        "time" : {
          "start" : 1662777474378,
          "stop" : 1662777474501,
          "duration" : 123
        }
      }, {
        "uid" : "e4a74b78713f8bfb",
        "status" : "failed",
        "statusDetails" : "The following error originated from your test code, not from Cypress.\n\n  > Given is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
        "time" : {
          "start" : 1662776520668,
          "stop" : 1662776520810,
          "duration" : 142
        }
      }, {
        "uid" : "c9cea5e97a315c10",
        "status" : "failed",
        "statusDetails" : "The following error originated from your test code, not from Cypress.\n\n  > Given is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
        "time" : {
          "start" : 1662776237426,
          "stop" : 1662776237582,
          "duration" : 156
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "8904cc2d1ed62861.json",
  "parameterValues" : [ ]
}